version: '3.7'
services:
  superdigital-api:
    build:
      context: .
      dockerfile: SuperDigital.Conta.Dockerfile
    container_name: superdigital-api
    restart: always    
    ports:
      - "8181:80"
    links:
      - postgres
    depends_on:
      - postgres      
  postgres:
    image: postgres
    container_name: 'postgres'
    ports:
      - "5432:5432"      
    environment:
      POSTGRES_PASSWORD: def4ult-pssw0rd8
      POSTGRES_USER: super_digital